# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 08:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firewalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.LineStringField(srid=3857)),
                ('type', models.IntegerField()),
                ('descript', models.CharField(max_length=70)),
            ],
        ),
    ]
