# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewalls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firewalls',
            old_name='geom',
            new_name='geo',
        ),
    ]
