# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewalls', '0002_auto_20181205_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firewalls',
            old_name='geo',
            new_name='geom',
        ),
    ]
